"""200+ investment tips for financial literacy education."""

TIPS = [
    {"icon": "🔢", "title": "The Rule of 72", "text": "Divide 72 by your expected return. The result tells you how many years it takes to double your money."},
    {"icon": "📈", "title": "Compound Interest", "text": "Albert Einstein called it the eighth wonder of the world. Start early and let time work for you — interest earns interest."},
    {"icon": "⏰", "title": "Time in the Market", "text": "It's more important how long you stay invested than finding the perfect moment to buy. Time in the market beats timing the market."},
    {"icon": "🎯", "title": "Diversification", "text": "Never put all your eggs in one basket. A mix of asset classes like stocks, gold, and bonds protects your portfolio."},
    {"icon": "🧘", "title": "Control Your Emotions", "text": "Fear and greed are the worst advisors in investing. Stick to your plan, even when the charts turn red."},
    {"icon": "📊", "title": "Dollar-Cost Averaging", "text": "By investing regularly each month, you buy more shares when prices are low and fewer when high."},
    {"icon": "💸", "title": "Understand Inflation", "text": "Money in a savings account loses purchasing power to inflation. Investing in real assets can offset this loss long-term."},
    {"icon": "🐻", "title": "Bear Markets", "text": "A bear market means falling prices (usually over 20%). Historically, every bear market was followed by an even stronger bull market."},
    {"icon": "📦", "title": "Use ETFs", "text": "Exchange Traded Funds track an entire market. They're cost-effective and an easy way to invest in hundreds of companies at once."},
    {"icon": "🛟", "title": "Emergency Fund First", "text": "Before investing, keep 3-6 months of expenses in a savings account. You won't be forced to sell stocks at the worst time."},
    {"icon": "💰", "title": "Minimize Fees", "text": "High fees eat your returns over decades. Always look for low-cost brokers and products."},
    {"icon": "🏢", "title": "Stocks = Ownership", "text": "When you buy a stock, you own a tiny piece of a real company. You benefit from their work and profits."},
    {"icon": "🏘️", "title": "Dividends", "text": "Some companies pay part of their profits directly to shareholders. It's like 'rent' for your invested capital."},
    {"icon": "😴", "title": "Know Your Risk Profile", "text": "Only invest as much in volatile assets as lets you sleep at night. Your well-being comes first."},
    {"icon": "⚖️", "title": "Rebalancing", "text": "Check once a year if your asset allocation still fits. Sell what grew too much, buy what's cheap."},
    {"icon": "🕐", "title": "Be Patient", "text": "Stock prices fluctuate short-term but trend upward long-term. A 10-15 year horizon dramatically reduces loss risk."},
    {"icon": "🐑", "title": "Avoid the Herd", "text": "Just because everyone's talking about a hype stock doesn't mean it's time to buy. Buy quality, not euphoria."},
    {"icon": "📏", "title": "Small Caps vs Blue Chips", "text": "Blue chips are established mega-corps. Small caps are smaller firms with more growth potential but higher risk."},
    {"icon": "💱", "title": "Currency Risk", "text": "When you invest in foreign stocks, your returns also fluctuate with the exchange rate."},
    {"icon": "📐", "title": "Real Returns", "text": "Real return = your gain minus inflation. Only this number shows how much more you can actually buy later."},
    {"icon": "🎢", "title": "Volatility", "text": "Volatility measures how much a price swings. It's the price you pay for higher return potential."},
    {"icon": "📚", "title": "Knowledge is Power", "text": "Never invest in something you don't understand. Take time to learn the basics of your investment products."},
    {"icon": "🇨🇭", "title": "Tax Considerations", "text": "In Switzerland, capital gains on securities are usually tax-free for private investors, but dividends are taxed as income."},
    {"icon": "🏦", "title": "Pillar 3a", "text": "Use private pension plans to save on taxes while investing long-term in securities for your retirement."},
    {"icon": "🤖", "title": "Passive Strategy", "text": "Studies show that passive investing in broad market indices beats almost all active professional strategies long-term."},
    {"icon": "🔄", "title": "Cyclical Sectors", "text": "Some sectors like tourism depend heavily on the economy. Defensive sectors like pharma are often more stable."},
    {"icon": "🧠", "title": "Psychological Barriers", "text": "Round numbers often act as psychological barriers for investors but have little fundamental significance."},
    {"icon": "📉", "title": "Interest Rate Risk", "text": "When interest rates rise, existing bond prices often fall. Stocks can also come under pressure."},
    {"icon": "🔎", "title": "Market Capitalization", "text": "Share price × total shares = market cap. It shows a company's total value on the stock exchange."},
    {"icon": "⚡", "title": "Correction vs. Crash", "text": "A correction is a 10% decline, a crash is over 20%. Both often offer attractive buying opportunities."},
    {"icon": "✨", "title": "Keep It Simple", "text": "A simple portfolio of 1-3 ETFs is often better than a complex one with 50 individual stocks."},
    {"icon": "🤔", "title": "Consume vs. Invest", "text": "Ask yourself before every purchase: Do I need this, or could these 100 CHF become 400 in 20 years?"},
    {"icon": "🔮", "title": "Future Trends", "text": "Don't just invest in what works today — think about which sectors will shape the world in 10 years."},
    {"icon": "🚕", "title": "Market Psychology", "text": "When taxi drivers start giving stock tips, it's often a sign the market is overheated."},
    {"icon": "📋", "title": "Withholding Tax", "text": "Foreign dividends often have withholding tax deducted. You can partially reclaim this through your tax return."},
    {"icon": "💧", "title": "Liquidity", "text": "Consider how easily you can convert your investment back to cash. Large-cap stocks are usually very liquid."},
    {"icon": "🥇", "title": "Gold as an Anchor", "text": "Gold doesn't pay interest but often serves as a 'safe haven' during crises."},
    {"icon": "🚫", "title": "Avoid Leverage", "text": "Never invest with borrowed money. Loan interest is almost always higher than expected stock returns."},
    {"icon": "📊", "title": "Total Expense Ratio", "text": "TER shows you annual ETF costs. The lower it is, the more return stays with you."},
    {"icon": "⚙️", "title": "Automate It", "text": "Set up a standing order for your savings plan. Make investing a habit you don't have to think about."},
    {"icon": "📈", "title": "Price-to-Earnings Ratio", "text": "P/E ratio compares a stock's price to its earnings. A high P/E may indicate an expensive stock or high growth expectations."},
    {"icon": "💔", "title": "Loss Tolerance", "text": "How would you feel if your portfolio dropped 30% tomorrow? Be honest with yourself."},
    {"icon": "👶", "title": "Start Small", "text": "You don't need to be a millionaire to start. Many savings plans begin at just 20 or 50 CHF per month."},
    {"icon": "🌍", "title": "Diversify Globally", "text": "Don't just invest in Swiss companies (home bias). Spread your money across the world."},
    {"icon": "🔁", "title": "Reinvest Dividends", "text": "Reinvest your dividends immediately into new shares. Only then does compound interest reach full power."},
    {"icon": "📝", "title": "Learn from Mistakes", "text": "Every investor makes mistakes. What matters is analyzing them and making more rational decisions next time."},
    {"icon": "🎯", "title": "Asset Allocation", "text": "How you split your money across classes affects returns more than picking individual stocks."},
    {"icon": "🧩", "title": "Market Efficiency", "text": "Assume all known information is already priced in. Don't try to outsmart the entire market."},
    {"icon": "🌱", "title": "Patience Pays", "text": "The stock market transfers money from the impatient to the patient. Give your investments time to grow."},
    {"icon": "🎉", "title": "Enjoy the Journey", "text": "Investing should be fun and give you security. Celebrate every small step toward financial freedom."},
    {"icon": "🏠", "title": "Real Estate vs Stocks", "text": "Real estate provides rental income and appreciation, but is illiquid. REITs offer real estate exposure with stock-like liquidity."},
    {"icon": "📱", "title": "Fintech Revolution", "text": "Modern apps make investing accessible to everyone. Take advantage of low-cost digital platforms."},
    {"icon": "🌐", "title": "Globalization", "text": "The world is interconnected. Events in one country can affect your portfolio across the globe."},
    {"icon": "🔋", "title": "Energy Transition", "text": "The shift to renewable energy creates investment opportunities in solar, wind, and battery technology."},
    {"icon": "💊", "title": "Healthcare Investing", "text": "An aging population drives demand for healthcare. Pharma and biotech stocks can be good long-term holdings."},
    {"icon": "🤝", "title": "Trust the Process", "text": "Consistent investing over decades beats trying to pick the next big winner. Process over prediction."},
    {"icon": "📰", "title": "News vs Reality", "text": "Financial news creates urgency and fear. Most headlines are noise — focus on long-term fundamentals."},
    {"icon": "🏋️", "title": "Financial Fitness", "text": "Like physical fitness, financial health requires discipline, consistency, and patience. Start your workout today."},
    {"icon": "🎓", "title": "Investment Literacy", "text": "Financial literacy is one of the most valuable skills you can develop. It pays dividends for life."},
    {"icon": "🌈", "title": "Think Long-Term", "text": "Short-term losses are temporary. Long-term gains are permanent. Keep your eyes on the horizon."},
    {"icon": "🗓️", "title": "Monthly Investing", "text": "Invest the same amount every month regardless of market conditions. Time smooths out volatility."},
    {"icon": "🎪", "title": "Avoid Speculation", "text": "Speculation is not investing. Know the difference between a calculated bet and a gamble."},
    {"icon": "🔑", "title": "Key Metrics", "text": "Learn P/E, P/B, dividend yield, and ROE. These four metrics tell you a lot about a company's value."},
    {"icon": "🧮", "title": "The Power of 10%", "text": "Saving and investing just 10% of your income consistently can build significant wealth over 20-30 years."},
    {"icon": "🌊", "title": "Ride the Waves", "text": "Markets are like the ocean — waves come and go, but the tide rises over time. Stay on the surfboard."},
    {"icon": "🧲", "title": "Value Traps", "text": "A cheap stock isn't always a good deal. Verify the company's fundamentals before buying the dip."},
    {"icon": "💎", "title": "Quality Over Quantity", "text": "Owning a few great companies beats owning many mediocre ones. Quality is king in long-term investing."},
    {"icon": "⚓", "title": "Anchor Bias", "text": "Don't cling to your purchase price. Evaluate investments based on current fundamentals, not what you paid."},
    {"icon": "🏆", "title": "Consistency Wins", "text": "The best investors aren't the smartest — they're the most consistent and disciplined."},
    {"icon": "📍", "title": "Geographic Diversification", "text": "Spread investments across regions. When one economy struggles, another often thrives."},
    {"icon": "🔐", "title": "Protect Your Capital", "text": "Warren Buffett's Rule #1: Never lose money. Rule #2: Never forget Rule #1. Capital preservation is key."},
    {"icon": "🎭", "title": "Contrarian Thinking", "text": "Be fearful when others are greedy, and greedy when others are fearful — Warren Buffett."},
    {"icon": "🧪", "title": "Research First", "text": "Before investing in any asset, spend at least as much time researching it as you would buying a new phone."},
    {"icon": "🏦", "title": "Central Bank Watching", "text": "Central bank decisions on interest rates move markets. Pay attention to Fed, ECB, and SNB announcements."},
    {"icon": "🌿", "title": "ESG Investing", "text": "Environmental, Social, and Governance criteria can help identify sustainable, future-proof companies."},
    {"icon": "📊", "title": "Track Your Performance", "text": "Keep a simple spreadsheet of your investments. What gets measured gets managed."},
    {"icon": "🎗️", "title": "Sunk Cost Fallacy", "text": "Don't hold a losing investment just because you've already lost money. Evaluate its future potential objectively."},
    {"icon": "🏗️", "title": "Build Wealth Gradually", "text": "Most millionaires built their wealth slowly over decades, not through one lucky trade."},
    {"icon": "🔬", "title": "Due Diligence", "text": "Always do your own research. Don't blindly follow influencers, friends, or financial media."},
    {"icon": "🎵", "title": "Ignore the Noise", "text": "Daily market movements are mostly noise. Focus on your long-term investment thesis and tune out the chatter."},
    {"icon": "⚠️", "title": "Beware of FOMO", "text": "Fear of missing out leads to buying at the top. Stay disciplined and follow your investment plan."},
    {"icon": "🌟", "title": "Start Before You're Ready", "text": "There's never a perfect time to start investing. The best time is now; the second best time is tomorrow."},
    {"icon": "📖", "title": "Read Financial Books", "text": "Books like 'The Intelligent Investor' and 'A Random Walk Down Wall Street' are timeless investment guides."},
    {"icon": "🗞️", "title": "Earnings Season", "text": "Companies report quarterly earnings. These reports can cause significant short-term price movements."},
    {"icon": "⛏️", "title": "Commodities Cycle", "text": "Commodity prices are cyclical. Oil, copper, and agricultural products follow supply and demand patterns."},
    {"icon": "🏛️", "title": "Government Bonds", "text": "Government bonds from stable countries are the bedrock of conservative portfolios and provide steady income."},
    {"icon": "🎲", "title": "Risk Management", "text": "Never risk more than you can afford to lose. Position sizing is as important as stock selection."},
    {"icon": "🌏", "title": "Emerging Markets Growth", "text": "Emerging markets like India and Southeast Asia offer high growth potential with added risk."},
    {"icon": "🧊", "title": "Cool Head in Crisis", "text": "The most money is made during crises — by those who keep a cool head while others panic."},
    {"icon": "💡", "title": "Innovation Premium", "text": "Companies that innovate tend to outperform long-term. Tech and healthcare lead in innovation spending."},
    {"icon": "🎋", "title": "Bamboo Investing", "text": "Like bamboo, which grows roots for years before shooting up, good investments take time to show results."},
    {"icon": "🧭", "title": "Have a Plan", "text": "Create a simple investment plan with clear goals, time horizon, and risk tolerance. Then stick to it."},
    {"icon": "🎯", "title": "Goal-Based Investing", "text": "Invest with specific goals: retirement, home purchase, education. Each goal may need a different strategy."},
    {"icon": "🔄", "title": "Market Cycles", "text": "Markets move in cycles: expansion, peak, contraction, trough. Understanding this reduces emotional decisions."},
    {"icon": "📞", "title": "Never Invest on Tips", "text": "Hot stock tips from friends or social media rarely work out. Do your own research before investing."},
    {"icon": "🏃", "title": "Marathon Not Sprint", "text": "Investing is a marathon, not a sprint. Slow and steady builds real wealth over time."},
    {"icon": "🔍", "title": "Read Annual Reports", "text": "Annual reports reveal a company's health. Learn to read balance sheets and income statements."},
    {"icon": "💵", "title": "Cash is a Position", "text": "Holding cash is also an investment decision. Sometimes waiting for better opportunities is wise."},
    {"icon": "🏔️", "title": "Swiss Stability", "text": "Switzerland's political stability and strong currency make Swiss investments a solid foundation."},
    {"icon": "💼", "title": "Invest in What You Know", "text": "Peter Lynch advises investing in companies you understand and use in daily life."},
    {"icon": "🌡️", "title": "Sentiment Indicators", "text": "Extreme fear or greed in the market often signals a turning point. Use contrarian indicators."},
    {"icon": "🎪", "title": "IPO Caution", "text": "IPOs are often overhyped. Wait for the dust to settle before buying newly listed companies."},
    {"icon": "🪙", "title": "Precious Metals", "text": "Gold, silver, and platinum serve as inflation hedges and portfolio diversifiers across all economic conditions."},
    {"icon": "📈", "title": "Trend Following", "text": "The trend is your friend. Don't fight strong market trends — instead, find ways to participate."},
    {"icon": "🏗️", "title": "Infrastructure Investing", "text": "Infrastructure investments provide stable, inflation-linked returns. Think roads, bridges, and utilities."},
    {"icon": "🔐", "title": "Security First", "text": "Use two-factor authentication on all brokerage accounts. Protect your investments from cyber threats."},
    {"icon": "💳", "title": "Debt Before Investing", "text": "Pay off high-interest debt before investing. The guaranteed return from debt repayment often exceeds market returns."},
    {"icon": "🌍", "title": "Think Global", "text": "The world economy is bigger than any single country. Global funds give you exposure to worldwide growth."},
    {"icon": "🎁", "title": "Tax-Free Gains", "text": "In many countries, long-term capital gains receive favorable tax treatment. Hold investments longer to benefit."},
    {"icon": "🧠", "title": "Behavioral Finance", "text": "Understanding cognitive biases like anchoring, loss aversion, and herd mentality improves your investment decisions."},
    {"icon": "📊", "title": "Correlation Matters", "text": "Invest in assets that don't move together. When stocks fall, bonds or gold may rise, reducing overall risk."},
    {"icon": "🌐", "title": "Index Funds Win", "text": "Over 15+ years, index funds beat 90% of active fund managers. Simple, low-cost, and effective."},
    {"icon": "💎", "title": "Diamond Hands Strategy", "text": "Holding through volatility requires conviction. If your thesis hasn't changed, don't let price movements scare you."},
    {"icon": "🧮", "title": "Compound Your Knowledge", "text": "Just like compound interest grows your money, compound learning grows your investment skills exponentially."},
    {"icon": "🏆", "title": "Learn from the Best", "text": "Study how Buffett, Lynch, and Bogle invest. Their principles have stood the test of time."},
    {"icon": "🌊", "title": "Dollar Strength Impact", "text": "A strong dollar can hurt emerging market investments but benefit US-based assets. Currency matters."},
    {"icon": "🎯", "title": "Set Stop Losses Wisely", "text": "Stop losses can protect your capital, but setting them too tight means you'll get stopped out by normal volatility."},
    {"icon": "🔀", "title": "Sector Diversification", "text": "Don't concentrate in one sector. Spread across technology, healthcare, finance, consumer goods, and energy."},
    {"icon": "📱", "title": "Mobile Trading Trap", "text": "Easy access to trading apps can lead to overtrading. Set rules for yourself and stick to them."},
    {"icon": "🏠", "title": "Home Bias Warning", "text": "Don't invest only in your home country. Swiss stocks are great but represent a tiny fraction of global markets."},
    {"icon": "📐", "title": "Risk-Adjusted Returns", "text": "A 10% return with 5% volatility is better than 12% return with 25% volatility. Always consider risk."},
    {"icon": "🔄", "title": "Tax-Loss Harvesting", "text": "Sell losing positions to offset gains in your tax return, then reinvest. A smart way to reduce taxes legally."},
    {"icon": "📊", "title": "Understand Beta", "text": "Beta measures a stock's volatility vs the market. Beta > 1 means more volatile, < 1 means less volatile."},
    {"icon": "🕰️", "title": "The Magic of 30 Years", "text": "Investing CHF 200/month at 7% return for 30 years gives you about CHF 230,000. Start now!"},
    {"icon": "⚗️", "title": "Diversification Formula", "text": "Own at least 15-20 different stocks across 5+ sectors for effective diversification. Or just buy an ETF."},
    {"icon": "🏁", "title": "Retirement Planning", "text": "Calculate how much you need for retirement. The earlier you start, the less you need to save each month."},
    {"icon": "🎲", "title": "Probability Thinking", "text": "Investing is about probabilities, not certainties. Diversify to ensure the odds are in your favor."},
    {"icon": "🔑", "title": "Financial Independence", "text": "Financial independence means your investments generate enough income to cover your expenses. It's achievable."},
    {"icon": "📊", "title": "Dividend Aristocrats", "text": "Companies that have increased dividends for 25+ years are called Dividend Aristocrats. They signal stability."},
    {"icon": "🌍", "title": "Climate Investing", "text": "Climate change creates both risks and opportunities. Clean energy, water management, and green tech are growing."},
    {"icon": "🧘", "title": "Mindful Investing", "text": "Before each trade, ask: Is this based on research or emotion? Mindfulness prevents costly impulse decisions."},
    {"icon": "📈", "title": "The Power of Compounding", "text": "At 7% annual return, CHF 10,000 becomes CHF 76,000 in 30 years. That's the power of compound growth."},
    {"icon": "🏦", "title": "Banking Sector Risks", "text": "Bank stocks can be volatile during financial crises. Diversify beyond the banking sector."},
    {"icon": "💡", "title": "First Mover Advantage", "text": "Early investors in transformative technologies often reap the highest rewards, but also face the highest risks."},
    {"icon": "⚖️", "title": "Risk Budget", "text": "Decide how much of your portfolio you're willing to risk. Keep your core holdings safe and experiment with the rest."},
    {"icon": "📱", "title": "Digital Currency Future", "text": "Central Bank Digital Currencies (CBDCs) are coming. They'll change how we think about money and payments."},
    {"icon": "🧩", "title": "Alternative Investments", "text": "Art, wine, collectibles, and farmland can diversify beyond traditional stocks and bonds."},
    {"icon": "🌟", "title": "Quality Matters Most", "text": "In the long run, high-quality companies with strong moats outperform cheap, low-quality stocks."},
    {"icon": "🎗️", "title": "Survivorship Bias", "text": "We only see the winning funds and stocks. Remember all the ones that failed — don't let survivorship bias fool you."},
    {"icon": "🏗️", "title": "Building a Core Portfolio", "text": "Start with 60-70% in broad index ETFs. Use the remaining 30-40% for individual picks if you want."},
    {"icon": "🧊", "title": "Cold Storage for Crypto", "text": "If you hold cryptocurrency, use a hardware wallet for large amounts. 'Not your keys, not your coins.'"},
    {"icon": "💰", "title": "Index Fund Superiority", "text": "Over the past 20 years, the average index fund has outperformed 85% of actively managed funds."},
    {"icon": "📊", "title": "Watch the Yield Curve", "text": "An inverted yield curve has predicted every U.S. recession since the 1950s. It's a powerful indicator."},
    {"icon": "🎓", "title": "Continuous Education", "text": "Markets evolve constantly. Keep learning about new instruments, technologies, and economic trends."},
    {"icon": "📐", "title": "Position Sizing", "text": "Never put more than 5-10% of your portfolio in a single stock. Position sizing is crucial risk management."},
    {"icon": "🏛️", "title": "Swiss Banking Advantage", "text": "Switzerland's strong banking regulations and political neutrality make it a global financial hub."},
    {"icon": "🔬", "title": "Biotech Opportunities", "text": "Biotech stocks can offer explosive growth but carry high risk. Balance with stable healthcare giants."},
    {"icon": "🌐", "title": "Supply Chain Investing", "text": "Understanding supply chains helps identify undervalued companies. The best investment isn't always the brand name."},
    {"icon": "🧮", "title": "Cost Averaging Works", "text": "Investing CHF 500/month for 10 years typically outperforms trying to invest CHF 60,000 at the 'perfect' time."},
    {"icon": "💎", "title": "Long-Term Outperformance", "text": "Over any 20-year period in history, a diversified stock portfolio has never lost money. Time heals all dips."},
    {"icon": "🌍", "title": "Trade Balance Impact", "text": "Countries with trade surpluses tend to have stronger currencies. This affects your international investments."},
    {"icon": "📈", "title": "Earnings Growth", "text": "Stock prices ultimately follow earnings growth. Companies that consistently grow earnings tend to outperform."},
    {"icon": "🏆", "title": "Winners Keep Winning", "text": "Momentum investing works: past winners tend to keep winning in the short-medium term."},
    {"icon": "🌱", "title": "Sustainable Investing", "text": "Companies with strong sustainability practices often have better long-term returns and lower risk."},
    {"icon": "🔄", "title": "Regular Reviews", "text": "Review your portfolio quarterly, rebalance annually. Don't check daily — it only causes anxiety."},
    {"icon": "💼", "title": "Career as Investment", "text": "Your biggest investment is your career. Skills and education have the best risk-adjusted return."},
    {"icon": "🏰", "title": "Competitive Moats", "text": "Look for companies with wide competitive moats: strong brands, network effects, high switching costs, or patents."},
    {"icon": "📉", "title": "Mean Reversion", "text": "Extreme market moves tend to revert to the mean. What goes up too fast often comes down, and vice versa."},
    {"icon": "🧠", "title": "Second-Level Thinking", "text": "First-level thinking: 'This company is great, buy it.' Second-level thinking: 'Everyone knows it's great, it's probably overpriced.'"},
    {"icon": "🌏", "title": "ASEAN Growth Story", "text": "Southeast Asian economies are growing rapidly. Vietnam, Indonesia, and the Philippines offer promising markets."},
    {"icon": "💡", "title": "Innovation Disruption", "text": "Disruptive companies can destroy incumbent businesses. Invest in the disruptors, not the disrupted."},
    {"icon": "🏗️", "title": "Bottom-Up Analysis", "text": "Focus on individual company quality rather than macro predictions. Good companies thrive in any environment."},
    {"icon": "📊", "title": "Free Cash Flow", "text": "Free cash flow is the money a company generates after expenses. It's more reliable than reported earnings."},
    {"icon": "🎯", "title": "Focus on What You Control", "text": "You can't control the market. Focus on what you can: savings rate, costs, diversification, and time horizon."},
    {"icon": "🌱", "title": "Teach the Next Generation", "text": "Teaching children about investing early gives them a head start. Financial literacy is life literacy."},
    {"icon": "⏳", "title": "Time Is Your Superpower", "text": "At 25 you have 40 years until retirement. That is more time than most companies exist — and enough for compound interest to do the heavy lifting."},
    {"icon": "🌱", "title": "Start Small, Think Big", "text": "CHF 100 per month invested at 7% for 35 years grows to over CHF 175,000. You only put in CHF 42,000. The rest is time doing its job."},
    {"icon": "🚀", "title": "Start Now, Not Later", "text": "Do not wait for the perfect moment — it does not exist. The best time to invest was yesterday. The second best is today."},
    {"icon": "🦹", "title": "Inflation Is the Silent Thief", "text": "Money sitting in a savings account loses purchasing power every year. Investing is not speculation — it is protecting yourself against inflation."},
    {"icon": "🎲", "title": "This Is Not Gambling", "text": "Long-term investing in the world market is not a bet on luck. It is a bet on global economic growth — which has continued for over 200 years."},
    {"icon": "🤖", "title": "Automate Your Investing", "text": "Set up a standing order to your investment account. Money you never see is money you never spend — and it grows quietly in the background."},
    {"icon": "🧺", "title": "Spread Your Risk", "text": "Diversification is free insurance. Spread your money across different countries, sectors and asset classes so one crash does not ruin everything."},
    {"icon": "👀", "title": "Check Less, Earn More", "text": "Studies show investors who check their portfolio less frequently make better decisions and achieve higher returns. Boredom is a strategy."},
    {"icon": "💪", "title": "Crashes Always End", "text": "Every crisis in stock market history ended with a new all-time high — the dot-com bust, 2008, COVID. The market has recovered every single time."},
    {"icon": "🧠", "title": "Ignore the Herd", "text": "When everyone is buying, the market is often overpriced. When everyone is selling, it is often cheap. Successful investors frequently act against the crowd."},
    {"icon": "🌍", "title": "Own the World", "text": "One ETF on the MSCI World gives you a stake in over 1,500 companies across 23 countries with a single click. Diversification for everyone."},
    {"icon": "💸", "title": "Fees Destroy Wealth", "text": "Fees are the only factor in investing you fully control. A 1% higher annual fee can cost you 25% of your final wealth over 30 years."},
    {"icon": "🎓", "title": "You Do Not Need to Be an Expert", "text": "Most professionals cannot beat the market long-term. A simple index fund is enough for most people — and that is not a compromise, it is the smart choice."},
    {"icon": "🛟", "title": "Build Your Safety Net First", "text": "Keep 3 to 6 months of living expenses in a savings account before investing. Then you never need to sell investments at the worst possible moment."},
    {"icon": "😴", "title": "Boring Is Beautiful", "text": "The best investment strategy feels like nothing is happening. Excitement in investing usually means expensive mistakes. Embrace the boredom."},
    {"icon": "⚖️", "title": "Know Your Risk Profile", "text": "Young and with decades ahead? You can afford more stocks — short-term crashes have time to recover. Your age is your safety net."},
    {"icon": "📰", "title": "News Is Noise", "text": "Bad headlines cause bad decisions. Markets price in news faster than you can react. Stick to your strategy no matter what the media is saying today."},
    {"icon": "🦁", "title": "Be Fearful When Others Are Greedy", "text": "Warren Buffett's most famous rule works both ways. Crisis is a sale. Quality companies at 30% off are still the same quality companies."},
    {"icon": "🐢", "title": "Patience Beats Intelligence", "text": "Warren Buffett has held some stocks for over 40 years. Not because he cannot sell — but because he knows patience is the most profitable strategy."},
    {"icon": "🪴", "title": "Every Amount Counts", "text": "Start with whatever feels right — even CHF 50 per month. The habit matters more than the amount. You can always increase it later."},
    {"icon": "🔗", "title": "Bonds Balance Your Portfolio", "text": "Bonds and stocks often move in opposite directions. Mixing both significantly reduces your portfolio's volatility without sacrificing too much return."},
    {"icon": "🧾", "title": "Use Tax Advantages", "text": "Many countries offer tax-advantaged retirement accounts. Using them is one of the simplest ways to boost long-term returns — do not leave that money on the table."},
    {"icon": "📉", "title": "Crashes Create Millionaires", "text": "The biggest stock market gains often happened within weeks of the biggest crashes. Investors who panicked and sold missed exactly that recovery."},
    {"icon": "🌳", "title": "Let It Grow Undisturbed", "text": "Think of your portfolio like a tree: the longer you let it grow without constantly uprooting it to check the roots, the stronger it becomes."},
    {"icon": "🤝", "title": "Robo-Advisors Do the Work", "text": "Automated investment platforms manage your portfolio based on your risk profile — low cost, transparent, and no expertise required to get started."},
    {"icon": "🎁", "title": "Invest for Future You", "text": "Your future self says thank you. Every franc you invest today is a gift to the version of you that exists in 30 years."},
    {"icon": "🙉", "title": "Ignore Hot Tips", "text": "By the time someone is raving about a stock at a party, the opportunity has usually already passed. Stick to your boring, diversified plan."},
    {"icon": "🏷️", "title": "Crises Are Clearance Sales", "text": "Companies like Apple or Nestlé sometimes go on sale during a market crash. Their quality has not changed — only their price tag has."},
    {"icon": "🪙", "title": "No Minimum Required", "text": "Many brokers allow investment savings plans from as little as CHF 1 per month. There is no excuse to wait. The first step is the most important."},
    {"icon": "🏭", "title": "Stocks Are Real Businesses", "text": "A share represents ownership in a real company with real employees and real products. You are investing in the world economy — not in abstract numbers."},
    {"icon": "🗓️", "title": "Match Risk to Time", "text": "The shorter your investment horizon, the more defensive you should be. The longer it is, the more equity you can comfortably hold."},
    {"icon": "🔄", "title": "Rebalance Once a Year", "text": "Check once a year that your portfolio allocation still matches your goals and adjust if needed. It takes about ten minutes and keeps your risk in check."},
    {"icon": "🗺️", "title": "Go Global", "text": "Investing only in your home country concentrates risk unnecessarily. A globally diversified portfolio smooths out local economic downturns."},
    {"icon": "🧗", "title": "Wealth Is for Everyone", "text": "Investing is not a luxury for the rich. It is a tool for anyone who wants to stop living month to month and start building something lasting."},
    {"icon": "🔍", "title": "Watch the Fine Print", "text": "A TER of 0.2% instead of 1.5% sounds like a rounding error — but over 30 years it can be the difference of more than CHF 50,000 in your pocket."},
    {"icon": "📃", "title": "Paper Losses Are Not Real", "text": "A loss is only locked in when you sell. As long as you stay invested, a drop in value is just a number on a screen — not a real loss."},
    {"icon": "🥇", "title": "Gold as a Stabiliser", "text": "Gold is not a growth engine — it is an anchor. A small allocation of 5 to 15% can reduce your portfolio's swings during market turbulence."},
    {"icon": "📅", "title": "The First Year Is the Hardest", "text": "Starting always feels uncomfortable. After the first year it becomes routine — and you will wonder why you did not begin sooner."},
    {"icon": "🧩", "title": "Strategy Over Speculation", "text": "Your investment strategy should be robust enough that it does not need daily adjustments. Set it, automate it and let it run."},
    {"icon": "🏋️", "title": "Consistency Beats Intensity", "text": "Investment discipline is like going to the gym: it is not about individual heroic sessions but about showing up month after month for years."},
    {"icon": "🎮", "title": "Simulate Before You Invest", "text": "Not sure how you would react to a 30% crash? Playing through market scenarios in a game like this one builds confidence before real money is on the line."},
    {"icon": "📐", "title": "Scale Up Over Time", "text": "As your salary grows, increase your monthly contribution even slightly each year. Small incremental raises compound into massive differences over decades."},
    {"icon": "✈️", "title": "Early Birds Fly Higher", "text": "Starting 10 years earlier often means needing to contribute only half as much per month to reach the same final wealth. Time is the best leverage available."},
    {"icon": "🌐", "title": "Anyone Can Do This", "text": "Investing does not require being wealthy, educated or lucky. It requires deciding to take responsibility for your financial future — and that is available to everyone."},
    {"icon": "🌏", "title": "Bet on Emerging Markets Too", "text": "Economies like India, Vietnam and Indonesia are growing fast. A small emerging market allocation adds growth potential and true global diversification."},
    {"icon": "🚫", "title": "Trading Less Is Earning More", "text": "The average private investor earns far less than the market return — because they trade too often and react to emotions. Less activity, more wealth."},
    {"icon": "🏢", "title": "You Are Already a Co-Owner", "text": "When you buy a share, you become a partial owner of that business. You sit alongside the largest investors in the world — with the same upside."},
    {"icon": "🛤️", "title": "Stay the Course", "text": "The worst investing decisions are made during the worst market moments. Define your strategy in calm times — and commit to it when markets get scary."},
    {"icon": "🎯", "title": "Good Enough Beats Perfect", "text": "The goal is not to invest perfectly. The goal is to start and keep going. A consistent, simple strategy crushes a perfect plan that never gets executed."},
    {"icon": "⚡", "title": "Delay Is Expensive", "text": "Every month you delay costs more than you think. At 7% annual return, waiting just one year at age 22 can cost you roughly four times that year's contributions in lost future growth."},
]
