"""Seed data: assets, events, decisions.
Asset avg_return & volatility calibrated from real market data (CSVs, Feb 2006 – Feb 2026).
"""

ASSETS = [
    # ── Equity Indices (real stats from CSV) ──
    {"id": "smi", "name": "SMI", "full_name": "Swiss Market Index", "category": "Equity Index", "icon": "🇨🇭", "avg_return": 0.027, "volatility": 0.166, "description": "Top 20 Swiss companies including Nestlé, Novartis, and Roche.", "info_text": "The Swiss Market Index (SMI) tracks the 20 largest companies on the SIX Swiss Exchange. Historical return: ~2.7%/yr, volatility: ~16.6%."},
    {"id": "eurostoxx50", "name": "Euro Stoxx 50", "full_name": "Euro Stoxx 50 Index", "category": "Equity Index", "icon": "🇪🇺", "avg_return": 0.023, "volatility": 0.213, "description": "50 leading Eurozone blue-chip companies.", "info_text": "The Euro Stoxx 50 covers 50 of the largest Eurozone companies. Historical return: ~2.3%/yr, volatility: ~21.3%."},
    {"id": "dowjones", "name": "Dow Jones", "full_name": "Dow Jones Industrial Average", "category": "Equity Index", "icon": "🇺🇸", "avg_return": 0.074, "volatility": 0.182, "description": "30 major US industrial companies including Apple and Microsoft.", "info_text": "The DJIA tracks 30 large US companies. Historical return: ~7.4%/yr, volatility: ~18.2%."},
    {"id": "nikkei", "name": "Nikkei 225", "full_name": "Nikkei 225 Index", "category": "Equity Index", "icon": "🇯🇵", "avg_return": 0.063, "volatility": 0.228, "description": "Japan's premier stock index — 225 leading companies.", "info_text": "The Nikkei 225 tracks Japan's largest companies. Historical return: ~6.3%/yr, volatility: ~22.8%."},
    {"id": "dax", "name": "DAX", "full_name": "DAX Total Return Index", "category": "Equity Index", "icon": "🇩🇪", "avg_return": 0.072, "volatility": 0.208, "description": "Germany's 40 largest companies — a Total Return index.", "info_text": "The DAX includes dividends in its calculation (Total Return). Historical return: ~7.2%/yr, volatility: ~20.8%."},
    # ── Single Stocks (real stats from CSV) ──
    {"id": "apple", "name": "Apple", "full_name": "Apple Inc. (AAPL)", "category": "Single Stock", "icon": "🍎", "avg_return": 0.233, "volatility": 0.316, "description": "World's most valuable tech company. 10,000%+ return since 2006.", "info_text": "Apple Inc. is one of the world's most valuable companies. Historical return: ~23.3%/yr, volatility: ~31.6%."},
    {"id": "nestle", "name": "Nestlé", "full_name": "Nestlé S.A.", "category": "Single Stock", "icon": "🍫", "avg_return": 0.035, "volatility": 0.175, "description": "Swiss food giant — a defensive stock with steady dividends.", "info_text": "Nestlé is the world's largest food company. Historical return: ~3.5%/yr, volatility: ~17.5%. A classic defensive stock."},
    {"id": "microsoft", "name": "Microsoft", "full_name": "Microsoft Corporation (MSFT)", "category": "Single Stock", "icon": "💻", "avg_return": 0.135, "volatility": 0.276, "description": "Software giant and cloud leader — 1,400%+ returns since 2006.", "info_text": "Microsoft dominates enterprise software and cloud computing. Historical return: ~13.5%/yr, volatility: ~27.6%."},
    {"id": "nvidia", "name": "NVIDIA", "full_name": "NVIDIA Corporation (NVDA)", "category": "Single Stock", "icon": "🎮", "avg_return": 0.308, "volatility": 0.511, "description": "AI and GPU leader — the highest-returning DJIA stock. Extreme volatility!", "info_text": "NVIDIA leads in AI chips and GPUs. Historical return: ~30.8%/yr, volatility: ~51.1%. Extremely high risk and reward."},
    {"id": "novartis", "name": "Novartis", "full_name": "Novartis AG", "category": "Single Stock", "icon": "💊", "avg_return": 0.038, "volatility": 0.196, "description": "Swiss pharma giant — lower risk, steady returns.", "info_text": "Novartis AG is a Swiss pharmaceutical company. Historical return: ~3.8%/yr, volatility: ~19.6%."},
    # ── Bonds (real stats from CSV) ──
    {"id": "bonds", "name": "Swiss Bonds", "full_name": "Swiss Bond Index AAA-BBB", "category": "Bonds", "icon": "📄", "avg_return": 0.018, "volatility": 0.032, "description": "Swiss investment-grade bonds — very low risk, modest return.", "info_text": "This index tracks Swiss bonds rated AAA to BBB. Historical return: ~1.8%/yr, volatility: ~3.2%. The safest asset class."},
    {"id": "global_bonds", "name": "Global Bonds", "full_name": "Bloomberg Global Aggregate Bond Index", "category": "Bonds", "icon": "🌍", "avg_return": 0.013, "volatility": 0.030, "description": "Broad global bond exposure, CHF hedged.", "info_text": "Bloomberg Global Aggregate tracks government and corporate bonds worldwide. Historical return: ~1.3%/yr, volatility: ~3.0%."},
    # ── Currencies (real stats from CSV) ──
    {"id": "usdchf", "name": "USD/CHF", "full_name": "US Dollar to Swiss Franc", "category": "Currency", "icon": "💵", "avg_return": -0.026, "volatility": 0.117, "description": "USD has lost ~40% vs CHF over 20 years. Currency risk is real.", "info_text": "USD/CHF shows the Swiss Franc's strength. Historical return: -2.6%/yr. The CHF is a safe haven currency."},
    {"id": "eurchf", "name": "EUR/CHF", "full_name": "Euro to Swiss Franc", "category": "Currency", "icon": "💶", "avg_return": -0.026, "volatility": 0.086, "description": "Euro has steadily weakened against the Swiss Franc.", "info_text": "EUR/CHF has declined ~42% since 2006. Historical return: -2.6%/yr, volatility: ~8.6%."},
    # ── Gold (real stats from CSV) ──
    {"id": "gold", "name": "Gold", "full_name": "Gold (XAU) in CHF", "category": "Commodity", "icon": "🥇", "avg_return": 0.083, "volatility": 0.175, "description": "Classic safe-haven — 422% gain in CHF over 20 years.", "info_text": "Gold has been a top performer: ~8.3%/yr return with moderate volatility. Acts as a hedge against inflation and crises."},
    # ── Crypto (not in CSV — kept as estimates) ──
    {"id": "btc", "name": "Bitcoin", "full_name": "Bitcoin (BTC)", "category": "Crypto", "icon": "₿", "avg_return": 0.40, "volatility": 0.70, "description": "The original cryptocurrency — extremely volatile but high growth potential.", "info_text": "Bitcoin is the first cryptocurrency, created in 2009. Fixed supply of 21 million coins. Extremely volatile but potentially high-reward."},
    {"id": "eth", "name": "Ethereum", "full_name": "Ethereum (ETH)", "category": "Crypto", "icon": "⟠", "avg_return": 0.35, "volatility": 0.75, "description": "Smart contract platform — second largest crypto by market cap.", "info_text": "Ethereum supports smart contracts, DeFi, and NFTs. Transitioned to Proof-of-Stake in 2022."},
]

EVENTS = [
    {"id": 1, "year": 2000, "title": "Dot-Com Bubble Burst", "description": "The internet stock bubble bursts. Tech stocks crash by over 75%.", "lesson": "Hype-driven investing is dangerous. Diversification protects you.", "icon": "💻", "impacts": {"Equity Index": -0.25, "Single Stock": -0.35, "Bonds": 0.05, "Currency": 0.0, "Commodity": 0.05, "Crypto": 0.0}},
    {"id": 2, "year": 2001, "title": "9/11 Attacks", "description": "Terrorist attacks shake the world economy. Markets plunge but recover.", "lesson": "Even after the worst events, markets have always recovered.", "icon": "🏢", "impacts": {"Equity Index": -0.15, "Single Stock": -0.20, "Bonds": 0.03, "Currency": -0.02, "Commodity": 0.10, "Crypto": 0.0}},
    {"id": 3, "year": 2008, "title": "Global Financial Crisis", "description": "Banks collapse worldwide. The S&P 500 loses over 50%.", "lesson": "Even the worst crash was followed by a 10-year bull market.", "icon": "🏦", "impacts": {"Equity Index": -0.40, "Single Stock": -0.45, "Bonds": 0.02, "Currency": -0.05, "Commodity": -0.10, "Crypto": 0.0}},
    {"id": 4, "year": 2011, "title": "European Debt Crisis", "description": "Greece, Spain, and Italy face debt problems. European stocks suffer.", "lesson": "Regional crises can affect your portfolio — global diversification helps.", "icon": "🇪🇺", "impacts": {"Equity Index": -0.15, "Single Stock": -0.10, "Bonds": -0.05, "Currency": -0.08, "Commodity": 0.10, "Crypto": 0.05}},
    {"id": 5, "year": 2015, "title": "Swiss Franc Shock (SNB)", "description": "The SNB removes the EUR/CHF floor. The franc surges 20% in minutes.", "lesson": "Currency risk is real. Central bank decisions can cause sudden moves.", "icon": "🇨🇭", "impacts": {"Equity Index": -0.10, "Single Stock": -0.12, "Bonds": 0.02, "Currency": -0.15, "Commodity": 0.05, "Crypto": 0.0}},
    {"id": 6, "year": 2017, "title": "Bitcoin Mania", "description": "Bitcoin surges from $1,000 to $20,000, then crashes 80%.", "lesson": "Speculative assets can surge — but chasing hype is not investing.", "icon": "🚀", "impacts": {"Equity Index": 0.05, "Single Stock": 0.05, "Bonds": 0.0, "Currency": 0.0, "Commodity": 0.0, "Crypto": 0.80}},
    {"id": 7, "year": 2020, "title": "COVID-19 Pandemic", "description": "Global lockdowns trigger the fastest market crash in history.", "lesson": "Those who stayed invested recovered in months.", "icon": "🦠", "impacts": {"Equity Index": -0.20, "Single Stock": -0.25, "Bonds": 0.03, "Currency": -0.03, "Commodity": 0.15, "Crypto": 0.30}},
    {"id": 8, "year": 2022, "title": "Interest Rate Shock", "description": "Central banks raise rates aggressively. Stocks and bonds fall together.", "lesson": "Inflation and rising rates can hurt even safe bonds. Stay diversified.", "icon": "📈", "impacts": {"Equity Index": -0.18, "Single Stock": -0.20, "Bonds": -0.15, "Currency": 0.05, "Commodity": 0.08, "Crypto": -0.50}},
    {"id": 9, "year": 2023, "title": "AI Boom", "description": "AI drives a massive tech rally. Magnificent 7 stocks surge over 100%.", "lesson": "Innovation creates opportunities — but don't overconcentrate.", "icon": "🤖", "impacts": {"Equity Index": 0.15, "Single Stock": 0.25, "Bonds": 0.02, "Currency": 0.0, "Commodity": 0.0, "Crypto": 0.20}},
    {"id": 10, "year": 2024, "title": "Global Recovery Rally", "description": "Markets hit all-time highs as inflation cools.", "lesson": "After every storm, the sun shines again.", "icon": "☀️", "impacts": {"Equity Index": 0.12, "Single Stock": 0.15, "Bonds": 0.05, "Currency": 0.02, "Commodity": 0.05, "Crypto": 0.40}},
]

DECISIONS = [
    {"id": 1, "title": "2008 Financial Crisis", "icon": "🏦", "description": "Banks are collapsing worldwide. Your portfolio just lost 35%. Panic everywhere.", "options": [{"text": "Sell everything — too risky!", "effect": -0.20, "feedback": "You sold at the bottom and missed the recovery."}, {"text": "Hold and wait it out", "effect": 0.0, "feedback": "Correct! Those who stayed invested experienced one of the strongest bull markets."}, {"text": "Buy more — stocks are cheap!", "effect": 0.15, "feedback": "Excellent! Buying during the crisis produced the best returns."}], "lesson": "Panic selling destroys returns. Staying calm during crashes is rewarded."},
    {"id": 2, "title": "European Debt Crisis 2011", "icon": "🇪🇺", "description": "Greece is on the brink of bankruptcy. The Euro is shaking.", "options": [{"text": "Dump European stocks", "effect": -0.10, "feedback": "The crisis was resolved and European stocks recovered."}, {"text": "Keep portfolio unchanged", "effect": 0.0, "feedback": "Good decision. The ECB stabilized the market."}, {"text": "Shift to Swiss Franc and Gold", "effect": 0.05, "feedback": "Gold and CHF did rise, but long-term you miss equity returns."}], "lesson": "Regional crises feel dramatic but are usually resolved."},
    {"id": 3, "title": "Swiss Franc Shock 2015", "icon": "🇨🇭", "description": "The SNB removes the EUR/CHF floor. The Franc surges 20% in minutes.", "options": [{"text": "Sell Swiss stocks immediately", "effect": -0.08, "feedback": "The panic was exaggerated. Swiss companies recovered quickly."}, {"text": "Wait and observe", "effect": 0.0, "feedback": "Right! After the shock, markets normalized."}, {"text": "Buy foreign stocks (now cheaper in CHF)", "effect": 0.10, "feedback": "Clever! The strong Franc made foreign stocks cheaper."}], "lesson": "Currency shocks are short-term."},
    {"id": 4, "title": "Brexit Referendum 2016", "icon": "🇬🇧", "description": "The UK votes to leave the EU. Markets are shocked. The Pound crashes.", "options": [{"text": "Sell British investments", "effect": -0.05, "feedback": "The UK market recovered quickly."}, {"text": "Change nothing", "effect": 0.0, "feedback": "Correct. Political events cause short-term volatility."}, {"text": "Shift to government bonds", "effect": -0.03, "feedback": "Bonds offered protection but you missed the stock recovery."}], "lesson": "Political shocks are usually irrelevant for long-term investors."},
    {"id": 5, "title": "COVID-19 Pandemic 2020", "icon": "🦠", "description": "Global lockdowns! The fastest crash in history: -34% in 23 days.", "options": [{"text": "Sell everything!", "effect": -0.25, "feedback": "The recovery was the fastest ever. Those who sold missed +75% returns."}, {"text": "Keep my savings plan running", "effect": 0.05, "feedback": "Perfect! Dollar-cost averaging in action!"}, {"text": "Buy more aggressively", "effect": 0.20, "feedback": "Fantastic! Those who bought in March 2020 doubled their investment."}], "lesson": "Even the worst pandemic couldn't stop markets permanently."},
    {"id": 6, "title": "Inflation Shock 2022", "icon": "📈", "description": "Inflation explodes to 8%+. Central banks raise rates aggressively.", "options": [{"text": "Exit stocks and hold cash", "effect": -0.12, "feedback": "Cash loses purchasing power at 8% inflation."}, {"text": "Stay broadly diversified", "effect": 0.0, "feedback": "Right! Commodities and value stocks profited."}, {"text": "Shift to commodities and gold", "effect": 0.08, "feedback": "Smart! Real assets perform well during inflation."}], "lesson": "Inflation is the saver's silent enemy."},
    {"id": 7, "title": "Credit Suisse Collapse 2023", "icon": "🏦", "description": "Credit Suisse is taken over by UBS. AT1 bonds become worthless.", "options": [{"text": "Sell all bank stocks", "effect": -0.08, "feedback": "The banking sector stabilized."}, {"text": "Wait — only one bank affected", "effect": 0.0, "feedback": "Right. It was an isolated problem, not systemic."}, {"text": "Buy UBS stock — bargain!", "effect": 0.12, "feedback": "Clever! UBS acquired CS cheaply and the stock rose."}], "lesson": "Not every bank crisis is like 2008."},
    {"id": 8, "title": "Crypto Crash & FTX Scandal", "icon": "💥", "description": "FTX collapses. Bitcoin falls below $16,000. Billions vanish.", "options": [{"text": "Sell all crypto", "effect": -0.05, "feedback": "Bitcoin later recovered to new all-time highs."}, {"text": "Keep a small crypto allocation (max 5%)", "effect": 0.03, "feedback": "Perfect! A small allocation is the smart approach."}, {"text": "Go all-in on Bitcoin!", "effect": -0.15, "feedback": "Too risky! Diversification is essential."}], "lesson": "Speculative assets belong in small doses only."},
    {"id": 9, "title": "AI Boom & Nvidia Rally", "icon": "🤖", "description": "ChatGPT sparks an AI hype. Nvidia multiplies in value.", "options": [{"text": "Go all-in on Nvidia and tech", "effect": 0.10, "feedback": "Short-term gain, but concentration risk!"}, {"text": "Hold a broad ETF", "effect": 0.05, "feedback": "Perfect! An MSCI World ETF already includes the biggest tech companies."}, {"text": "Avoid tech — it's just hype", "effect": -0.05, "feedback": "AI wasn't just hype — it was a real revolution."}], "lesson": "Trends can be real, but avoid concentration risk."},
    {"id": 10, "title": "Ukraine War & Energy Crisis", "icon": "⚡", "description": "Russia invades Ukraine. Gas prices explode. Europe faces an energy crisis.", "options": [{"text": "Avoid European stocks completely", "effect": -0.08, "feedback": "Europe found alternatives. Many stocks recovered."}, {"text": "Stay diversified, add some energy", "effect": 0.05, "feedback": "Right! Energy companies profited."}, {"text": "Invest in defense stocks", "effect": 0.08, "feedback": "Defense companies did surge."}], "lesson": "Geopolitical crises create winners and losers."},
    {"id": 11, "title": "Negative Interest Rates", "icon": "📉", "description": "The central bank introduces negative interest rates. You're paying the bank!", "options": [{"text": "Hoard cash under the mattress", "effect": -0.05, "feedback": "Cash loses even more to inflation."}, {"text": "Invest in dividend stocks", "effect": 0.08, "feedback": "Great idea! Dividend stocks offered positive real returns."}, {"text": "Buy real estate funds", "effect": 0.06, "feedback": "Smart! Low rates drove real estate prices up."}], "lesson": "When saving costs money, investing becomes a necessity."},
    {"id": 12, "title": "GameStop & Meme Stock Frenzy", "icon": "🎮", "description": "Reddit users drive GameStop up 1,500%. FOMO is spreading.", "options": [{"text": "Jump in immediately! 🚀", "effect": -0.15, "feedback": "Most late buyers lost massive amounts."}, {"text": "Watch but don't invest", "effect": 0.0, "feedback": "Smart! Not a rational investment decision."}, {"text": "Put a small fun amount in (max 2%)", "effect": -0.01, "feedback": "Fair enough! A tiny bet doesn't hurt."}], "lesson": "FOMO is not an investment plan."},
]
